baseURL = 'https://t3easy.github.io/talks'
languageCode = 'en-us'
title = 't3easy talks'

theme = "reveal-hugo"

[markup.goldmark.renderer]
unsafe = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true